### ISSUE TITLE
Anaconda Navigator打不开:Navigator Error

### ISSUE THREAD

**Issue by HuangCongQing** [HuangCongQing/Python#29]
```
Traceback (most recent call last):
File "D:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "D:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
window = run_app(splash)
File "D:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
window = MainWindow(splash=splash)
File "D:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
self.api = AnacondaAPI()
File "D:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "D:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
self._conda_api = CondaAPI()
File "D:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
CONDA_API = _CondaAPI()
File "D:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
self.set_conda_prefix()
File "D:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```

**Comment by HuangCongQing** [comment]
https://blog.csdn.net/weixin_42529892/article/details/81503261

**Comment by HuangCongQing** [comment]
[使用*Anaconda* *Navigator安装python*包](https://www.baidu.com/link?url=rDd99FiXW75LPDHXBQuks1CyMWGnM_GlHVRlonyrL5RFB-zp3LXJLD7Ge-YTbKTCaRmeqgzDO0TzMQvE_M0fiae2VbueoUxBGMUj3E4Ay4K&wd=&eqid=e26e208a0000c979000000065cd6b959)
